#!/usr/bin/env bash
# Interactive first-time setup. Collects the values that are specific to
# your own environment - cluster contexts, namespaces, and test credentials -
# and writes them to two files that are excluded from version control:
#
#   .env                                          cluster contexts/namespaces/credentials,
#                                                  sourced by every script via lib/common.sh
#   helm-overlays/orchestration-users.local.yaml   a local override of
#                                                  helm-overlays/orchestration-users.yaml,
#                                                  used automatically once .env is sourced
#
# Nothing in this script touches the tracked template files under
# helm-overlays/ - it only ever writes the two files above, so there's no
# risk of accidentally committing real credentials into this repository.
#
# Usage: ./scripts/quick-setup.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
USERS_FILE="$REPO_ROOT/helm-overlays/orchestration-users.local.yaml"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }

# prompt LABEL DEFAULT -> echoes the user's answer, or DEFAULT if left blank.
prompt() {
  local label="$1" default="$2" value
  read -r -p "$label [$default]: " value
  echo "${value:-$default}"
}

# random_secret -> a 32-character alphanumeric string, used as a default
# whenever a credential is left blank rather than forcing the user to invent
# one.
random_secret() {
  if command -v openssl > /dev/null 2>&1; then
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
  else
    head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32
  fi
}

bold "=== Environment setup ==="
echo "This collects the values needed to point these scripts at your own"
echo "dual-region cluster, instead of hand-editing scripts/lib/common.sh."
echo

if command -v oc > /dev/null 2>&1; then
  KUBE_CLI=oc
elif command -v kubectl > /dev/null 2>&1; then
  KUBE_CLI=kubectl
else
  echo "Neither 'oc' nor 'kubectl' was found on PATH - install one before continuing." >&2
  exit 1
fi

echo "Available $KUBE_CLI contexts:"
"$KUBE_CLI" config get-contexts -o name 2>/dev/null | sed 's/^/  /' || echo "  (none found)"
echo

CONTEXT_EAST=$(prompt "Kube context for the East (primary) region" "camunda-dr-east")
NS_EAST=$(prompt "Namespace in the East region" "camunda-dr-east-ns")
CONTEXT_WEST=$(prompt "Kube context for the West (secondary) region" "camunda-dr-west")
NS_WEST=$(prompt "Namespace in the West region" "camunda-dr-west-ns")

echo
echo "Basic-auth credentials for the Zeebe/Operate/Tasklist test user, and"
echo "for the Connectors service user. Leave either password blank to have"
echo "one generated for you."
AUTH_USER=$(prompt "Test user username" "venom")
AUTH_PASS=$(prompt "Test user password (blank = generate one)" "$(random_secret)")
CONNECTORS_PASS=$(prompt "Connectors password (blank = generate one)" "$(random_secret)")

echo
echo "MinIO's own root credentials are normally read automatically at"
echo "runtime from each region's elasticsearch-env-secret Secret, once"
echo "Elasticsearch is deployed - you only need to set these here if you're"
echo "also using them to deploy MinIO itself for the first time (see"
echo "cluster-setup/minio-deployment.example.yaml)."
MINIO_ACCESS_KEY=$(prompt "MinIO access key (blank = generate one)" "$(random_secret | head -c 16)")
MINIO_SECRET_KEY=$(prompt "MinIO secret key (blank = generate one)" "$(random_secret)")

cat > "$ENV_FILE" <<EOF
# Generated by scripts/quick-setup.sh. Not tracked by git (see .gitignore).
# Source this before running any script in this repository:
#   source .env
export CONTEXT_EAST="$CONTEXT_EAST"
export NS_EAST="$NS_EAST"
export CONTEXT_WEST="$CONTEXT_WEST"
export NS_WEST="$NS_WEST"
export AUTH_USER="$AUTH_USER"
export AUTH_PASS="$AUTH_PASS"
export MINIO_ACCESS_KEY="$MINIO_ACCESS_KEY"
export MINIO_SECRET_KEY="$MINIO_SECRET_KEY"
export USERS_VALUES="$USERS_FILE"
EOF
chmod 600 "$ENV_FILE"

cat > "$USERS_FILE" <<EOF
# Generated by scripts/quick-setup.sh - a local override of
# helm-overlays/orchestration-users.yaml populated with real credentials.
# Not tracked by git (see .gitignore). Used automatically in place of the
# checked-in template once USERS_VALUES is set by sourcing .env.
orchestration:
  security:
    initialization:
      users:
      - username: connectors
        password: $CONNECTORS_PASS
        name: Connector User
        email: connector@example.com
      - username: $AUTH_USER
        password: $AUTH_PASS
        name: Test User
        email: ${AUTH_USER}@example.com
EOF
chmod 600 "$USERS_FILE"

echo
bold "Done. Wrote:"
echo "  $ENV_FILE"
echo "  $USERS_FILE"
echo
bold "Next steps:"
echo "  1. source .env"
echo "  2. If Camunda isn't deployed yet in both regions, follow CLUSTER_SETUP.md"
echo "     first - it uses these same generated values, plus the reference"
echo "     manifests under cluster-setup/."
echo "  3. Once both regions are healthy: ./scripts/reset-cluster.sh"
echo "  4. Then run the test sequence starting with ./scripts/test/00-baseline.sh"
echo "     (see the Quick start section in README.md)."
